import re
import os

file_path = r'c:\Users\engan\Desktop\Lojas\backend\models\models.py'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    r'\bphone = Column': 'telefone = Column',
    r'\bwebsite = Column': 'site = Column',
    r'\bpublisher = Column': 'editora = Column',
    r'default=\"Active\"': 'default=\"Ativo\"',
    r'\bSTATE = \"Estadual\"': 'ESTADUAL = \"Estadual\"',
    r'\bYORK = \"Rito York\"': 'YORK = \"Rito York\"',
    r'\bSCHRODER = \"Rito Schroder\"': 'SCHRODER = \"Rito Schroder\"',
    r'\bBRAZILIAN = \"Rito Brasileiro\"': 'BRASILEIRO = \"Rito Brasileiro\"',
    r'\bMODERN = \"Rito Moderno\"': 'MODERNO = \"Rito Moderno\"',
    r'\bADONHIRAMITE = \"Rito Adonhiramita\"': 'ADONHIRAMITA = \"Rito Adonhiramita\"',
    r'\bRER = \"Rito Escocês Retificado\"': 'RER = \"Rito Escocês Retificado\"',
    r'\bLODGE = \"Loja\"': 'LOJA = \"Loja\"',
    r'\bOBEDIENCE = \"Obediência\"': 'OBEDIENCIA = \"Obediência\"',
    r'\bSUBOBEDIENCE = \"Subobediência\"': 'SUBOBEDIENCIA = \"Subobediência\"',
    r'\bSPOUSE = \"Esposa\"': 'ESPOSA = \"Esposa\"',
    r'\bSON = \"Filho\"': 'FILHO = \"Filho\"',
    r'\bDAUGHTER = \"Filha\"': 'FILHA = \"Filha\"',
    r'\bFATHER = \"Pai\"': 'PAI = \"Pai\"',
    r'\bMOTHER = \"Mãe\"': 'MAE = \"Mãe\"',
    r'\bAPPRENTICE = \"Aprendiz\"': 'APRENDIZ = \"Aprendiz\"',
    r'\bFELLOW = \"Companheiro\"': 'COMPANHEIRO = \"Companheiro\"',
    r'\bMASTER = \"Mestre\"': 'MESTRE = \"Mestre\"',
    r'\bINSTALLED_MASTER = \"Mestre Instalado\"': 'MESTRE_INSTALADO = \"Mestre Instalado\"',
    r'\bPENDING = \"Pendente\"': 'PENDENTE = \"Pendente\"',
    r'\bAPPROVED = \"Aprovado\"': 'APROVADO = \"Aprovado\"',
    r'\bREJECTED = \"Rejeitado\"': 'REJEITADO = \"Rejeitado\"',
    r'\bGRANT = \"Concedida\"': 'CONCEDIDA = \"Concedida\"',
    r'\bREVOKE = \"Revogada\"': 'REVOGADA = \"Revogada\"',
    r'\bACTIVE = \"Ativo\"': 'ATIVO = \"Ativo\"',
    r'\bINACTIVE = \"Inativo\"': 'INATIVO = \"Inativo\"',
    r'\bDISABLED = \"Desativado\"': 'DESATIVADO = \"Desativado\"',
    r'\bREGULAR = \"Regular\"': 'REGULAR = \"Regular\"',
    r'\bIRREGULAR = \"Irregular\"': 'IRREGULAR = \"Irregular\"',
    r'\bEMERITUS = \"Emérito\"': 'EMERITO = \"Emérito\"',
    r'\bREMITTED = \"Remido\"': 'REMIDO = \"Remido\"',
    r'\bHONORARY = \"Honorário\"': 'HONORARIO = \"Honorário\"',
    r'\bORDINARY = \"Ordinária\"': 'ORDINARIA = \"Ordinária\"',
    r'\bMAGNA = \"Magna\"': 'MAGNA = \"Magna\"',
    r'\bEXTRAORDINARY = \"Extraordinária\"': 'EXTRAORDINARIA = \"Extraordinária\"',
    r'\bADMINISTRATIVE = \"Administrativa\"': 'ADMINISTRATIVA = \"Administrativa\"',
    r'\bFINANCE = \"Finanças\"': 'FINANCAS = \"Finanças\"',
    r'\bAFFILIATION_REGULARIZATION = \"Filiação e Regularização\"': 'FILIACAO_REGULARIZACAO = \"Filiação e Regularização\"',
    r'\bELECTORAL = \"Eleitoral\"': 'ELEITORAL = \"Eleitoral\"',
    r'\bRITUALISTIC_BANQUET = \"Banquete Ritualístico\"': 'BANQUETE_RITUALISTICO = \"Banquete Ritualístico\"',
    r'\bINITIATION = \"Iniciação\"': 'INICIACAO = \"Iniciação\"',
    r'\bELEVATION = \"Elevação\"': 'ELEVACAO = \"Elevação\"',
    r'\bEXALTATION = \"Exaltação\"': 'EXALTACAO = \"Exaltação\"',
    r'\bINSTALLATION = \"Posse\"': 'POSSE = \"Posse\"',
    r'\bINSTALLATION_WORSHIPFUL = \"Instalação\"': 'INSTALACAO = \"Instalação\"',
    r'\bSTANDARD_CONSECRATION = \"Sagração de Estandarte\"': 'SAGRACAO_ESTANDARTE = \"Sagração de Estandarte\"',
    r'\bLODGE_REGULARIZATION = \"Regularização de Loja\"': 'REGULARIZACAO_LOJA = \"Regularização de Loja\"',
    r'\bTEMPLE_CONSECRATION = \"Sagração de Templo\"': 'SAGRACAO_TEMPLO = \"Sagração de Templo\"',
    r'\bLOWTON_ADOPTION = \"Adoção de Lowtons\"': 'ADOCAO_LOWTONS = \"Adoção de Lowtons\"',
    r'\bMATRIMONIAL_CONSECRATION = \"Consagração e Exaltação matrimonial\"': 'CONSAGRACAO_MATRIMONIAL = \"Consagração e Exaltação matrimonial\"',
    r'\bFUNERAL_POMPS = \"Pompas Fúnebres\"': 'POMPAS_FUNEBRES = \"Pompas Fúnebres\"',
    r'\bCONFERENCE = \"Conferência\"': 'CONFERENCIA = \"Conferência\"',
    r'\bLECTURE = \"Palestra\"': 'PALESTRA = \"Palestra\"',
    r'\bFESTIVE = \"Festiva\"': 'FESTIVA = \"Festiva\"',
    r'\bCIVIC_CULTURAL = \"Cívico-cultural\"': 'CIVICO_CULTURAL = \"Cívico-cultural\"',
    r'\bGENERAL_GM_ELECTION = \"Eleições de Grão-Mestre Geral e Adjuntos\"': 'ELEICAO_GM_GERAL = \"Eleições de Grão-Mestre Geral e Adjuntos\"',
    r'\bSTATE_GM_ELECTION = \"Eleição de Grão-Mestre Estadual e Adjuntos\"': 'ELEICAO_GM_ESTADUAL = \"Eleição de Grão-Mestre Estadual e Adjuntos\"',
    r'\bDF_GM_ELECTION = \"Eleição de Grão Mestre do Distrito Federal e Adjuntos\"': 'ELEICAO_GM_DF = \"Eleição de Grão Mestre do Distrito Federal e Adjuntos\"',
    r'\bFAMILY_COUNCIL = \"Conselho de Família\"': 'CONSELHO_FAMILIA = \"Conselho de Família\"',
    r'\bEX_OFFICIO_PLACET = \"Concessão de placet ex-officio\"': 'PLACET_EX_OFFICIO = \"Concessão de placet ex-officio\"',
    r'\bSTATUTE_CHANGE = \"Alteração de Estatuto\"': 'ALTERACAO_ESTATUTO = \"Alteração de Estatuto\"',
    r'\bRITE_CHANGE = \"Mudança de Rito\"': 'MUDANCA_RITO = \"Mudança de Rito\"',
    r'\bORIENT_CHANGE = \"Mudança de Oriente\"': 'MUDANCA_ORIENTE = \"Mudança de Oriente\"',
    r'\bDISTINCTIVE_TITLE_CHANGE = \"Mudança de Título Distintivo\"': 'MUDANCA_TITULO_DISTINTIVO = \"Mudança de Título Distintivo\"',
    r'\bLODGE_MERGER = \"Fusão ou Incorporação de Lojas\"': 'FUSAO_LOJAS = \"Fusão ou Incorporação de Lojas\"',
    r'\bPERMANENT = \"Permanente\"': 'PERMANENTE = \"Permanente\"',
    r'\bTEMPORARY = \"Temporária\"': 'TEMPORARIA = \"Temporária\"',
    r'\bNEW = \"Novo\"': 'NOVO = \"Novo\"',
    r'\bGOOD = \"Bom\"': 'BOM = \"Bom\"',
    r'\bFAIR = \"Regular\"': 'REGULAR = \"Regular\"',
    r'\bPOOR = \"Ruim\"': 'RUIM = \"Ruim\"',
    r'\bAVAILABLE = \"Disponível\"': 'DISPONIVEL = \"Disponível\"',
    r'\bLOANED = \"Emprestado\"': 'EMPRESTADO = \"Emprestado\"',
    r'\bRESERVED = \"Reservado\"': 'RESERVADO = \"Reservado\"',
    r'\bLOST = \"Extraviado\"': 'EXTRAVIADO = \"Extraviado\"',
    r'\bRETURNED = \"Devolvido\"': 'DEVOLVIDO = \"Devolvido\"',
    r'\bLATE = \"Atrasado\"': 'ATRASADO = \"Atrasado\"',
    r'\bWAITING = \"Aguardando\"': 'AGUARDANDO = \"Aguardando\"',
    r'\bNOTIFIED = \"Notificado\"': 'NOTIFICADO = \"Notificado\"',
    r'\bFULFILLED = \"Atendido\"': 'ATENDIDO = \"Atendido\"',
    r'\bCANCELED = \"Cancelado\"': 'CANCELADO = \"Cancelado\"',
    r'\bEXPIRED = \"Expirado\"': 'EXPIRADO = \"Expirado\"',
    r'\bREGULATIONS = \"Regulamentos\"': 'REGULAMENTOS = \"Regulamentos\"',
    r'\bACTS = \"Atos\"': 'ATOS = \"Atos\"',
    r'\bDOCUMENTS = \"Documentos\"': 'DOCUMENTOS = \"Documentos\"',
    r'\bBULLETINS = \"Boletins\"': 'BOLETINS = \"Boletins\"',
    r'\bARTICLE = \"Artigo\"': 'ARTIGO = \"Artigo\"',
    r'\bDRAFT = \"Rascunho\"': 'RASCUNHO = \"Rascunho\"',
    r'\bPUBLISHED = \"Publicado\"': 'PUBLICADO = \"Publicado\"',
    r'\bARCHIVED = \"Arquivado\"': 'ARQUIVADO = \"Arquivado\"',
    r'\bTipoSessaoEnum\.ORDINARY': 'TipoSessaoEnum.ORDINARIA',
    r'\bTipoSessaoEnum\.MAGNA': 'TipoSessaoEnum.MAGNA',
    r'\bTipoSessaoEnum\.EXTRAORDINARY': 'TipoSessaoEnum.EXTRAORDINARIA',
    r'\bSubtipoSessaoEnum\.ADMINISTRATIVE': 'SubtipoSessaoEnum.ADMINISTRATIVA',
    r'\bSubtipoSessaoEnum\.FINANCE': 'SubtipoSessaoEnum.FINANCAS',
    r'\bSubtipoSessaoEnum\.AFFILIATION_REGULARIZATION': 'SubtipoSessaoEnum.FILIACAO_REGULARIZACAO',
    r'\bSubtipoSessaoEnum\.ELECTORAL': 'SubtipoSessaoEnum.ELEITORAL',
    r'\bSubtipoSessaoEnum\.RITUALISTIC_BANQUET': 'SubtipoSessaoEnum.BANQUETE_RITUALISTICO',
    r'\bSubtipoSessaoEnum\.INITIATION': 'SubtipoSessaoEnum.INICIACAO',
    r'\bSubtipoSessaoEnum\.ELEVATION': 'SubtipoSessaoEnum.ELEVACAO',
    r'\bSubtipoSessaoEnum\.EXALTATION': 'SubtipoSessaoEnum.EXALTACAO',
    r'\bSubtipoSessaoEnum\.INSTALLATION': 'SubtipoSessaoEnum.POSSE',
    r'\bSubtipoSessaoEnum\.INSTALLATION_WORSHIPFUL': 'SubtipoSessaoEnum.INSTALACAO',
    r'\bSubtipoSessaoEnum\.STANDARD_CONSECRATION': 'SubtipoSessaoEnum.SAGRACAO_ESTANDARTE',
    r'\bSubtipoSessaoEnum\.LODGE_REGULARIZATION': 'SubtipoSessaoEnum.REGULARIZACAO_LOJA',
    r'\bSubtipoSessaoEnum\.TEMPLE_CONSECRATION': 'SubtipoSessaoEnum.SAGRACAO_TEMPLO',
    r'\bSubtipoSessaoEnum\.LOWTON_ADOPTION': 'SubtipoSessaoEnum.ADOCAO_LOWTONS',
    r'\bSubtipoSessaoEnum\.MATRIMONIAL_CONSECRATION': 'SubtipoSessaoEnum.CONSAGRACAO_MATRIMONIAL',
    r'\bSubtipoSessaoEnum\.FUNERAL_POMPS': 'SubtipoSessaoEnum.POMPAS_FUNEBRES',
    r'\bSubtipoSessaoEnum\.CONFERENCE': 'SubtipoSessaoEnum.CONFERENCIA',
    r'\bSubtipoSessaoEnum\.LECTURE': 'SubtipoSessaoEnum.PALESTRA',
    r'\bSubtipoSessaoEnum\.FESTIVE': 'SubtipoSessaoEnum.FESTIVA',
    r'\bSubtipoSessaoEnum\.CIVIC_CULTURAL': 'SubtipoSessaoEnum.CIVICO_CULTURAL',
    r'\bSubtipoSessaoEnum\.GENERAL_GM_ELECTION': 'SubtipoSessaoEnum.ELEICAO_GM_GERAL',
    r'\bSubtipoSessaoEnum\.STATE_GM_ELECTION': 'SubtipoSessaoEnum.ELEICAO_GM_ESTADUAL',
    r'\bSubtipoSessaoEnum\.DF_GM_ELECTION': 'SubtipoSessaoEnum.ELEICAO_GM_DF',
    r'\bSubtipoSessaoEnum\.FAMILY_COUNCIL': 'SubtipoSessaoEnum.CONSELHO_FAMILIA',
    r'\bSubtipoSessaoEnum\.EX_OFFICIO_PLACET': 'SubtipoSessaoEnum.PLACET_EX_OFFICIO',
    r'\bSubtipoSessaoEnum\.STATUTE_CHANGE': 'SubtipoSessaoEnum.ALTERACAO_ESTATUTO',
    r'\bSubtipoSessaoEnum\.RITE_CHANGE': 'SubtipoSessaoEnum.MUDANCA_RITO',
    r'\bSubtipoSessaoEnum\.ORIENT_CHANGE': 'SubtipoSessaoEnum.MUDANCA_ORIENTE',
    r'\bSubtipoSessaoEnum\.DISTINCTIVE_TITLE_CHANGE': 'SubtipoSessaoEnum.MUDANCA_TITULO_DISTINTIVO',
    r'\bSubtipoSessaoEnum\.LODGE_MERGER': 'SubtipoSessaoEnum.FUSAO_LOJAS',
}

for k, v in replacements.items():
    content = re.sub(k, v, content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
